name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show info
        run: npm version

      - name: Install deps
        run: npm ci

      - name: Build, apply formatting, lint, package and run unit tests
        run: npm run all

      - name: Style check
        run: npm run format-check

  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show info
        run: npm version

      - name: Setup BATS
        uses: ./

      - name: BATS test
        run: bats __tests__/integration.bats
